### ISSUE TITLE
カメラ起動しっぱなしになる問題

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/cappuccino-app#17]
developブランチで確認した

## 再現方法
1. scan画面を開く
2. カメラの準備ができる前に他画面に遷移する

## 起きる事

ずっとカメラが起動してる状態になる

## 想定される挙動

カメラは起動されないか、起動してもすぐに消える

**Comment by su8ru** [comment]
これ、技術的に難しい気がします

- WebRTC API を叩いているので、どうしようもなさそう
- もしかしたら可能かもしれないけど、[react-qr-reader](https://github.com/JodusNodus/react-qr-reader) の内部実装の問題

結局のところ

- 遷移後、さらにもう一度カメラを使おうとしても問題なく使える
- タブをキルしちゃえば問題なく使えるようになる（なりませんか？）

**Comment by su8ru** [comment]
`streamTrack.stop` は WebRTC API との接続が完了してから手に入るみたい。

[index\.js \- JodusNodus/react\-qr\-reader \- GitHub1s](https://github1s.com/JodusNodus/react-qr-reader/blob/HEAD/src/index.js)

```js
  handleVideo(stream) {
    // 省略

    const streamTrack = stream.getTracks()[0]
    // Assign `stopCamera` so the track can be stopped once component is cleared
    this.stopCamera = streamTrack.stop.bind(streamTrack)

    // 省略
```
