### ISSUE TITLE
Check-in の人数・色表示がわかりづらい

### ISSUE THREAD

**Issue by su8ru** [afes-website/cappuccino-app#218]
わかりづらいんですよ

どうしよう

あと「中断して最初からやり直す」も変える

**Comment by su8ru** [comment]
member_all 分の guest 枠を予め表示してそれを埋めていく感じとか？

**Comment by ibuki2003** [comment]
プログレスバーくらいでいいのでは

ボタンは「予約読取にもどる」とか？

**Comment by su8ru** [comment]
Guest の背景をリストバンド色ベタでいいかも　リストバンドみがあるし
