### ISSUE TITLE
情報取得系の要件定義

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/cappuccino-app#27]
- Exhibition関係
  - [x] 各ユーザーの抱えてる展示に関する情報(滞在人数・きゃぱ・ろぐ)
- General
  - [x] Home画面からリストバンドQRコードを読み込んでその人の状況・ログを取得できるようにする
  - [x] 現在の各展示の滞在人数・キャパシティをチェックできるようにする
    - 円グラフの100%を滞在人数じゃなくてキャパシティにしておくと良い気がします
- Admin+Reservation
  - [ ] Reservation/Guest QR どちらを読み込んでも個人情報とログがすべて見れる画面を用意する
    - 一応各情報はタップして初めて表示される、みたいにしておくと必要以上に情報が表示されるのを防げていい気がする。
    - 普通に個人情報の扱いに関係するので要検討 :warning:
  - [ ] 個人情報による検索。 これも要検討 :warning:
  - [ ] ログの全取得・検索ができるとなおよし

**Comment by su8ru** [comment]
いろいろエンドポイントが足りなくないですか…？

- 入退場のログを取得できるエンドポイントが存在しません
- 全ての `ActivityLog` を取得できるエンドポイントが存在しません
- guest から reservation を知るすべがありません
  search の query に guest_id を追加すれば可能？
