### ISSUE TITLE
Pull to Refresh がブラウザ自体と衝突する

### ISSUE THREAD

**Issue by su8ru** [afes-website/cappuccino-app#45]
#43 で実装された Pull to Refresh のバグというか不具合というか

- [x] Android
- [ ] iOS・iPadOS

css の `overscroll-behavior` を使えば解消できそうだが…………

Safari :anger::anger::anger:

![image](https://user-images.githubusercontent.com/33474143/112456500-2df03c00-8d9e-11eb-80b8-497307b866e3.png)

mobile.twitter.com は問題なくスクロールできるイメージがあるので見てみたら、
html 要素に overflow を指定して、他のメニューたちを fixed で固定する実装になっていそう

それでなぜブラウザ自体のスクロールとの衝突が起きないのかはよくわからないけど、一考の価値はありそう
(~~そもそも iPhone で衝突しないのかすら不明だけど~~ →しませんでした)

**Comment by su8ru** [comment]
泥 PWA では解消済み

**Comment by ibuki2003** [comment]
pull to reload自体をなくしてreloadボタンを設置ですぐ解決すると思われ という話をした
